@API_HostAddress = http://localhost:5056/api/v1

POST {{API_HostAddress}}/customers/
Content-Type: application/json
Accept: application/json

{
  "name": "John Doe",
  "email": "john@contoso.com",
  "address": {
    "street": "Street John",
    "city": "São Paulo",
    "state": "SP",
    "zipCode": "12345-678",
    "country": "Brasil"
  }
}

###
@CustomerId = 87E1FED1-6872-4B80-8D6D-6D518A6D0740

GET {{API_HostAddress}}/customers/{{CustomerId}}
Content-Type: application/json

###

PUT {{API_HostAddress}}/customers/{{CustomerId}}
Content-Type: application/json

{
  "name": "John"
}

###
